-- TASK 6
CREATE OR REPLACE TRIGGER trg_change_group_members_num
AFTER INSERT OR DELETE OR UPDATE ON STUDENTS
FOR EACH ROW 
BEGIN 
	IF INSERTING THEN 
		UPDATE GROUPS SET C_VAL = C_VAL + 1 WHERE ID = :NEW.GROUP_ID;
	
	ELSIF UPDATING THEN
		IF :OLD.GROUP_ID != :NEW.GROUP_ID THEN
			UPDATE GROUPS SET C_VAL = C_VAL + 1 WHERE ID = :NEW.GROUP_ID;
			UPDATE GROUPS SET C_VAL = C_VAL - 1 WHERE ID = :OLD.GROUP_ID;
		END IF;
	
	ELSIF DELETING THEN
		UPDATE GROUPS SET C_VAL = C_VAL - 1 WHERE ID = :OLD.GROUP_ID;
	END IF;
END;

--SELECT * FROM STUDENTS;
--SELECT * FROM GROUPS;
--INSERT INTO GROUPS (NAME, C_VAL) VALUES ('test_group_0', 0);
--INSERT INTO STUDENTS (NAME, GROUP_ID) VALUES ('test_student2', 1); 
--DELETE FROM STUDENTS WHERE ID = 25
--UPDATE STUDENTS SET GROUP_ID = 11 WHERE ID = 24
